In [23]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("Relax.csv", sep=';')

In [12]:
df.head(5)

,Ngày,PS-Open,PS-High,PS-Low,PS-Close,CS-Open,CS-High,CS-Low,CS-Close,KL_PS(K),KL_CS(M),K?t qu? Trade (Giá),PS H-L,CS H-L,CS C-O,CS - PS,CS(C)-PS(C)
0,15-Thg7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
1,14-Thg7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
2,13-Thg7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
3,12-Thg7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0
4,11-Thg7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0

In [14]:
df.dtypes

Ngày                   object
PS-Open                object
PS-High                object
PS-Low                 object
PS-Close               object
CS-Open                object
CS-High                object
CS-Low                 object
CS-Close               object
KL_PS(K)               object
KL_CS(M)               object
K?t qu? Trade (Giá)    object
PS H-L                 object
CS H-L                 object
CS C-O                 object
CS - PS                object
CS(C)-PS(C)            object
dtype: object

In [17]:
df.tail()

,Ngày,PS-Open,PS-High,PS-Low,PS-Close,CS-Open,CS-High,CS-Low,CS-Close,KL_PS(K),KL_CS(M),K?t qu? Trade (Giá),PS H-L,CS H-L,CS C-O,CS - PS,CS(C)-PS(C)
63,15-Thg4,NaN,NaN,NaN,NaN,"1514,89","1518,85","1491,26","1493,74",NaN,"181,765",NaN,0,"27,59","-21,15",NaN,NaN
64,14-Thg4,NaN,NaN,NaN,NaN,"1526,49","1534,28","1517,07","1518,01",NaN,"119,609",NaN,0,"17,21","-8,48",NaN,NaN
65,13-Thg4,NaN,NaN,NaN,NaN,"1512,37","1526,44","1506,45","1525,39",NaN,"143,872",NaN,0,"19,99","13,02",NaN,NaN
66,12-Thg4,NaN,NaN,NaN,NaN,"1530,3","1532,03","1506,41","1507,2",NaN,"152,482",NaN,0,"25,62","-23,1",NaN,NaN
67,08-Thg4,NaN,NaN,NaN,NaN,"1541,78","1547,6","1524,31","1524,31",NaN,"156,336",NaN,0,"23,29","-17,47",NaN,NaN

In [20]:
df.index

RangeIndex(start=0, stop=68, step=1)

In [22]:
df.columns

Index(['Ngày', 'PS-Open', 'PS-High', 'PS-Low', 'PS-Close', 'CS-Open',
       'CS-High', 'CS-Low', 'CS-Close', 'KL_PS(K)', 'KL_CS(M)',
       'K?t qu? Trade (Giá)', 'PS H-L', 'CS H-L', 'CS C-O', 'CS - PS ',
       'CS(C)-PS(C)'],
      dtype='object')

In [27]:
df.to_numpy()

array([['15-Thg7', nan, nan, ..., '0', '0', '0'],
       ['14-Thg7', nan, nan, ..., '0', '0', '0'],
       ['13-Thg7', nan, nan, ..., '0', '0', '0'],
       ...,
       ['13-Thg4', nan, nan, ..., '13,02', nan, nan],
       ['12-Thg4', nan, nan, ..., '-23,1', nan, nan],
       ['08-Thg4', nan, nan, ..., '-17,47', nan, nan]], dtype=object)

In [29]:
df.describe()

,Ngày,PS-Open,PS-High,PS-Low,PS-Close,CS-Open,CS-High,CS-Low,CS-Close,KL_PS(K),KL_CS(M),K?t qu? Trade (Giá),PS H-L,CS H-L,CS C-O,CS - PS,CS(C)-PS(C)
count,68,53,53,53,53,62,62,62,62,35,62,31,68,68,68,59,59
unique,68,50,53,49,48,62,62,62,62,35,62,24,50,63,63,53,53
top,15-Thg7,1275,"1226,2",1234,1315,"1212,36","1229,23","1209,97","1229,23","319,336","98,639",0,0,0,0,0,0
freq,1,2,1,3,3,1,1,1,1,1,1,5,15,6,6,6,6

In [31]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,58,59,60,61,62,63,64,65,66,67
Ngày,15-Thg7,14-Thg7,13-Thg7,12-Thg7,11-Thg7,08-Thg7,07-Thg7,06-Thg7,05-Thg7,04-Thg7,...,22-Thg4,21-Thg4,20-Thg4,19-Thg4,18-Thg4,15-Thg4,14-Thg4,13-Thg4,12-Thg4,08-Thg4
PS-Open,NaN,NaN,NaN,NaN,NaN,NaN,"1215,7","1234,8","1248,3",1247,...,"1442,3",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PS-High,NaN,NaN,NaN,NaN,NaN,NaN,"1226,2","1234,8","1251,9","1252,1",...,"1459,8",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PS-Low,NaN,NaN,NaN,NaN,NaN,NaN,1213,"1213,4",1234,"1238,1",...,"1434,7",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PS-Close,NaN,NaN,NaN,NaN,NaN,NaN,1225,1218,"1234,9",1242,...,1445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS-Open,NaN,NaN,NaN,NaN,NaN,NaN,"1212,36","1241,19","1252,48","1256,2",...,"1439,32","1434,77","1440,9","1471,63","1493,17","1514,89","1526,49","1512,37","1530,3","1541,78"
CS-High,NaN,NaN,NaN,NaN,NaN,NaN,"1229,23","1241,19","1256,47","1260,72",...,"1455,15","1452,41","1453,81","1478,5","1493,24","1518,85","1534,28","1526,44","1532,03","1547,6"
CS-Low,NaN,NaN,NaN,NaN,NaN,NaN,"1209,97","1211,94","1239,8","1244,5",...,"1419,05","1422,7","1434,87","1440,61","1466,73","1491,26","1517,07","1506,45","1506,41","1524,31"
CS-Close,NaN,NaN,NaN,NaN,NaN,NaN,"1229,23","1211,94","1242,05","1248,37",...,"1444,32","1426,87","1435,5","1440,61","1468,25","1493,74","1518,01","1525,39","1507,2","1524,31"
KL_PS(K),NaN,NaN,NaN,NaN,NaN,NaN,"319,336","399,286","332,002","245,644",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KL_CS(M),NaN,NaN,NaN,NaN,NaN,NaN,"98,639","131,18","162,031","112,84",...,"150,755","172,359","150,222","156,62","194,442","181,765","119,609","143,872","152,482","156,336"
K?t qu? Trade (Giá),NaN,NaN,NaN,NaN,NaN,NaN,"-4,2",-2,-5,-5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PS H-L,0,0,0,0,0,0,"13,2","21,4","17,9",14,...,"25,1",0,0,0,0,0,0,0,0,0
CS H-L,0,0,0,0,0,0,"19,26","29,25","16,67","16,22",...,"36,1","29,71","18,94","37,89","26,51","27,59","17,21","19,99","25,62","23,29"
CS C-O,0,0,0,0,0,0,"16,87","-29,25","-10,43","-7,83",...,5,"-7,9","-5,4","-31,02","-24,92","-21,15","-8,48","13,02","-23,1","-17,47"
CS - PS,0,0,0,0,0,0,"-6,06","-7,85","1,23","-2,22",...,-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CS(C)-PS(C),0,0,0,0,0,0,"4,23","-6,06","7,15","6,37",...,"-0,68",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
df = df.sort_values(by="Ngày")

In [36]:
df.sort_index(axis=1,ascending=False)

,PS-Open,PS-Low,PS-High,PS-Close,PS H-L,Ngày,KL_PS(K),KL_CS(M),K?t qu? Trade (Giá),CS-Open,CS-Low,CS-High,CS-Close,CS(C)-PS(C),CS H-L,CS C-O,CS - PS
0,NaN,NaN,NaN,NaN,0,15-Thg7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
1,NaN,NaN,NaN,NaN,0,14-Thg7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
2,NaN,NaN,NaN,NaN,0,13-Thg7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
3,NaN,NaN,NaN,NaN,0,12-Thg7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
4,NaN,NaN,NaN,NaN,0,11-Thg7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,NaN,NaN,NaN,NaN,0,15-Thg4,NaN,"181,765",NaN,"1514,89","1491,26","1518,85","1493,74",NaN,"27,59","-21,15",NaN
64,NaN,NaN,NaN,NaN,0,14-Thg4,NaN,"119,609",NaN,"1526,49","1517,07","1534,28","1518,01",NaN,"17,21","-8,48",NaN
65,NaN,NaN,NaN,NaN,0,13-Thg4,NaN,"143,872",NaN,"1512,37","1506,45","1526,44","1525,39",NaN,"19,99","13,02",NaN
66,NaN,NaN,NaN,NaN,0,12-Thg4,NaN,"152,482",NaN,"1530,3","1506,41","1532,03","1507,2",NaN,"25,62","-23,1",NaN
67,NaN,NaN,NaN,NaN,0,08-Thg4,NaN,"156,336",NaN,"1541,78","1524,31","1547,6","1524,31",NaN,"23,29","-17,47",NaN

In [47]:
df.head(15)

,Ngày,PS-Open,PS-High,PS-Low,PS-Close,CS-Open,CS-High,CS-Low,CS-Close,KL_PS(K),KL_CS(M),K?t qu? Trade (Giá),PS H-L,CS H-L,CS C-O,CS - PS,CS(C)-PS(C)
32,01-Thg6,"1318,5","1337,5",1316,1326,"1329,02","1341,47","1323,07","1335,49","325,936","127,582","5,993","21,5","18,4","6,47","3,1","9,49"
10,01-Thg7,1241,"1243,5","1221,5",1242,"1247,7","1255,67","1225,64","1252,24","330,352","118,891",4,22,"30,03","4,54","-8,03","10,24"
31,02-Thg6,1311,1330,1311,1315,"1339,12","1342,47","1319,85","1325,49","253,048","133,903","4,087",19,"22,62","-13,63","-3,62","10,49"
30,03-Thg6,1318,"1323,9","1305,6","1318,5","1323,09","1329,9","1313,4","1327,4","233,505","100,18","1,9946","18,3","16,5","4,31","1,8","8,9"
52,04-Thg5,"1408,3","1409,9",1383,1383,"1415,43","1415,45","1389,59","1389,59",NaN,"114,19",NaN,"26,9","25,86","-25,84","1,04","6,59"
9,04-Thg7,1247,"1252,1","1238,1",1242,"1256,2","1260,72","1244,5","1248,37","245,644","112,84",-5,14,"16,22","-7,83","-2,22","6,37"
51,05-Thg5,1392,"1403,6","1372,6","1402,5","1402,6","1405,43","1373,42","1404,88",NaN,"122,134",NaN,31,"32,01","2,28","-1,01","2,38"
8,05-Thg7,"1248,3","1251,9",1234,"1234,9","1252,48","1256,47","1239,8","1242,05","332,002","162,031",-5,"17,9","16,67","-10,43","1,23","7,15"
50,06-Thg5,1382,"1396,3","1358,8",1362,"1399,54","1399,54",1371,"1373,21",NaN,"129,907",NaN,"37,5","28,54","-26,33","8,96","11,21"
29,06-Thg6,"1320,7",1332,1315,1315,"1328,73","1336,96","1320,97","1327,04","224,785","132,834","2,194",17,"15,99","-1,69","1,01","12,04"
7,06-Thg7,"1234,8","1234,8","1213,4",1218,"1241,19","1241,19","1211,94","1211,94","399,286","131,18",-2,"21,4","29,25","-29,25","-7,85","-6,06"
28,07-Thg6,1315,"1315,5","1293,3",1315,"1323,19","1324,27","1297,98","1324,37","278,664","153,981",0,"22,2","26,29","1,18","-4,09","9,37"
6,07-Thg7,"1215,7","1226,2",1213,1225,"1212,36","1229,23","1209,97","1229,23","319,336","98,639","-4,2","13,2","19,26","16,87","-6,06","4,23"
67,08-Thg4,NaN,NaN,NaN,NaN,"1541,78","1547,6","1524,31","1524,31",NaN,"156,336",NaN,0,"23,29","-17,47",NaN,NaN
27,08-Thg6,1321,1342,"1319,8",1333,"1328,95","1348,4","1325,65","1342,03","267,43","163,072","2,246","22,2","22,75","13,08","-0,55","9,03"